const AppRegistry=new Map(),SystemBus=new EventTarget();
const Storage={get(k,f=null){try{const v=localStorage.getItem(`arcadeos:${k}`);return v==null?f:JSON.parse(v)}catch{return f}},set(k,v){try{localStorage.setItem(`arcadeos:${k}`,JSON.stringify(v))}catch{}},clear(){Object.keys(localStorage).filter(k=>k.startsWith('arcadeos:')).forEach(k=>localStorage.removeItem(k))}};
function registerApp(app){if(!app?.id||!app?.title||typeof app.render!=='function')throw Error('Invalid ArcadeOS app');AppRegistry.set(app.id,app)}
const appCard=a=>`<button class="app-card" data-open="${a.id}"><b>${a.icon||'◈'}</b><strong>${a.name||a.title}</strong><span>${a.description||''}</span></button>`;
registerApp({id:'library',icon:'▦',title:'APP LIBRARY',name:'App Library',description:'Installed ArcadeOS applications',render:()=>`<div class="app-grid">${[...AppRegistry.values()].filter(a=>a.id!=='library').map(appCard).join('')}</div>`});
registerApp({id:'terminal',icon:'>_',title:'TERMINAL',name:'Terminal',description:'Command-line system console',render:()=>`<div class="terminal" data-terminal-output>ArcadeOS shell v2.4\nType <strong>help</strong> to see commands.\n\n<span>guest@arcade:~$</span> <input class="terminal-input" data-terminal-input autofocus></div>`});
registerApp({id:'notes',icon:'✦',title:'NOTES',name:'Notes',description:'Persistent local scratchpad',render:()=>`<textarea class="notes" data-notes placeholder="Write something...">${escapeHtml(Storage.get('notes',''))}</textarea>`});
registerApp({id:'settings',icon:'⚙',title:'SYSTEM CONFIG',name:'System Config',description:'Theme, motion and local data controls',render:()=>`<div class="settings-list"><div class="setting"><div><strong>Visual theme</strong><small>Cycle system accent palette</small></div><button data-cycle-theme>CYCLE</button></div><div class="setting"><div><strong>Local data</strong><small>Clear ArcadeOS preferences and notes</small></div><button data-clear-storage>CLEAR</button></div><div class="setting"><div><strong>Motion</strong><small>Toggle interface animation</small></div><button data-toggle-motion>TOGGLE</button></div></div>`});
registerApp({id:'about',icon:'A',title:'ABOUT ARCADEOS',name:'About ArcadeOS',description:'Architecture and migration status',render:()=>`<div class="about"><p class="eyebrow">SYSTEM BUILD 2.4</p><h2>A browser becomes an arcade operating system.</h2><p>ArcadeOS is an independent browser desktop by <strong>Manav Agarwal</strong>.</p><p>Architecture: <code>registry · events · native modules · local persistence</code></p></div>`});
['snake','breakout','pong'].forEach((id,i)=>registerApp({id,icon:['◉','▤','↔'][i],title:['NEON SNAKE','NEON BREAKOUT','NEON PONG'][i],name:['Neon Snake','Neon Breakout','Neon Pong'][i],description:['Grid-based keyboard arcade game','Paddle-and-brick arcade game','Play against the system AI'][i],render:()=>gameShell(id,i===2?'PLAYER':'SCORE',i===0?'ARROWS / WASD':i===1?'LEFT / RIGHT':'UP / DOWN')}));
function gameShell(id,label,controls){return `<div class="snake-wrap"><canvas class="snake-board" width="420" height="420" data-game="${id}"></canvas><div class="snake-meta"><span>${label} <b data-score>0</b></span><span>${controls}</span><button class="primary" data-restart-game="${id}">RESTART</button></div></div>`}
const layer=document.querySelector('[data-window-layer]'),template=document.querySelector('#window-template');let topZ=40,windowOffset=0;
window.addEventListener('DOMContentLoaded',()=>{const t=setTimeout(()=>document.querySelector('[data-boot]')?.classList.add('is-done'),900);window.addEventListener('pagehide',()=>clearTimeout(t),{once:true});updateClock();setInterval(updateClock,1000);document.addEventListener('click',handleClick);SystemBus.dispatchEvent(new CustomEvent('system:ready'))});
function handleClick(e){const o=e.target.closest('[data-open]');if(o){openApp(o.dataset.open);return}const w=e.target.closest('.os-window');if(!w)return;if(e.target.closest('[data-close]'))return destroyWindow(w);if(e.target.closest('[data-minimize]'))w.classList.add('is-min');if(e.target.closest('[data-maximize]'))w.classList.toggle('is-max');if(e.target.closest('[data-cycle-theme]'))cycleTheme();if(e.target.closest('[data-clear-storage]')){Storage.clear();toast('LOCAL DATA CLEARED')}if(e.target.closest('[data-toggle-motion]')){document.body.classList.toggle('reduce-motion');Storage.set('reduceMotion',document.body.classList.contains('reduce-motion'));toast('MOTION MODE UPDATED')}const r=e.target.closest('[data-restart-game]');if(r)startGame(w,r.dataset.restartGame)}
function openApp(id){const app=AppRegistry.get(id);if(!app)return;const ex=layer.querySelector(`[data-app="${id}"]`);if(ex){ex.classList.remove('is-min');return focusWindow(ex)}const n=template.content.firstElementChild.cloneNode(true);n.dataset.app=id;n.querySelector('.window-title').textContent=app.title;n.querySelector('.window-content').innerHTML=app.render();windowOffset=(windowOffset+24)%120;n.style.left=`calc(50% + ${windowOffset}px)`;n.style.top=`calc(48% + ${windowOffset/3}px)`;layer.appendChild(n);focusWindow(n);enableDrag(n);bindApp(n,id);SystemBus.dispatchEvent(new CustomEvent('app:opened',{detail:{id}}))}
function bindApp(w,id){if(id==='notes'){const n=w.querySelector('[data-notes]');n?.addEventListener('input',()=>Storage.set('notes',n.value))}if(id==='terminal')initTerminal(w);if(['snake','breakout','pong'].includes(id))startGame(w,id)}
function destroyWindow(w){w._cleanup?.();w.remove();SystemBus.dispatchEvent(new CustomEvent('app:closed',{detail:{id:w.dataset.app}}))}function focusWindow(w){w.style.zIndex=String(++topZ)}
function enableDrag(w){const h=w.querySelector('[data-drag-handle]');let a=false,sx=0,sy=0,sl=0,st=0,p=null;h.addEventListener('pointerdown',e=>{if(e.target.closest('button')||w.classList.contains('is-max'))return;a=true;p=e.pointerId;focusWindow(w);try{h.setPointerCapture(p)}catch{}const r=w.getBoundingClientRect();sx=e.clientX;sy=e.clientY;sl=r.left;st=r.top;w.style.transform='none';w.style.left=`${r.left}px`;w.style.top=`${r.top}px`});h.addEventListener('pointermove',e=>{if(!a)return;w.style.left=`${Math.max(0,Math.min(innerWidth-w.offsetWidth,sl+e.clientX-sx))}px`;w.style.top=`${Math.max(0,Math.min(innerHeight-w.offsetHeight-54,st+e.clientY-sy))}px`});const stop=()=>{a=false;if(p!=null){try{h.releasePointerCapture(p)}catch{}p=null}};['pointerup','pointercancel'].forEach(x=>h.addEventListener(x,stop));h.addEventListener('lostpointercapture',()=>a=false);w.addEventListener('pointerdown',()=>focusWindow(w))}
function initTerminal(w){const i=w.querySelector('[data-terminal-input]'),o=w.querySelector('[data-terminal-output]');i?.focus();i?.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const raw=i.value.trim(),line=document.createElement('div');line.innerHTML=`<span>guest@arcade:~$</span> ${escapeHtml(raw)}<br>${runCommand(raw.toLowerCase())}`;o.insertBefore(line,i);i.value='';o.scrollTop=o.scrollHeight})}
function runCommand(c){if(c==='help')return 'Commands: help, apps, about, date, theme, open &lt;app&gt;';if(c==='apps')return [...AppRegistry.keys()].join(' · ');if(c==='about')return 'ArcadeOS v2.4 by Manav Agarwal.';if(c==='date')return new Date().toString();if(c==='theme'){cycleTheme();return 'Theme cycled.'}if(c.startsWith('open ')){const q=c.slice(5).replace(/\s+/g,''),a={neonsnake:'snake',neonbreakout:'breakout',neonpong:'pong'},id=a[q]||q;if(AppRegistry.has(id)){openApp(id);return`Launching ${AppRegistry.get(id).name}...`}return`Unknown app: ${escapeHtml(q)}`}return c?`Command not found: ${escapeHtml(c)}`:''}
const cheat=(id,m)=>window.ArcadeOS?.cheats?.enabled&&window.ArcadeOS.cheats.hasModifier(id,m),speed=()=>window.ArcadeOS?.cheats?.getSpeedScale?.()||1,mult=(id)=>cheat(id,'score_multiplier')?2:1;
function startGame(w,id){w._cleanup?.();if(id==='snake')initSnake(w);if(id==='breakout')initBreakout(w);if(id==='pong')initPong(w)}
function keyboardController(map,fn){const h=e=>{const m=map[e.key.toLowerCase()]||map[e.key];if(m){e.preventDefault();fn(m)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)}
function initSnake(w){const c=w.querySelector('[data-game="snake"]');if(!c)return;const x=c.getContext('2d'),cell=21;let s=[{x:10,y:10},{x:9,y:10},{x:8,y:10}],d={x:1,y:0},n={...d},f=spawn(),score=0,alive=true;const off=keyboardController({arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]},m=>{if(m[0]!==-d.x||m[1]!==-d.y)n={x:m[0],y:m[1]}});let timer;const loop=()=>{timer=setTimeout(()=>{if(!alive)return;d=n;let h={x:s[0].x+d.x,y:s[0].y+d.y};if(cheat('snake','invincible_walls'))h={x:(h.x+20)%20,y:(h.y+20)%20};if(h.x<0||h.y<0||h.x>=20||h.y>=20||s.some(p=>p.x===h.x&&p.y===h.y)){alive=false;SystemBus.dispatchEvent(new CustomEvent('game:score',{detail:{id:'snake',score}}));toast(`GAME OVER // SCORE ${score}`);return}s.unshift(h);if(h.x===f.x&&h.y===f.y){score+=mult('snake');f=spawn()}else s.pop();w.querySelector('[data-score]').textContent=score;draw();loop()},115/speed())};function spawn(){return{x:Math.floor(Math.random()*20),y:Math.floor(Math.random()*20)}}const cmd=e=>{if(e.detail?.gameId==='snake'&&e.detail.modifier==='spawn_food')f={x:(s[0].x+d.x+20)%20,y:(s[0].y+d.y+20)%20}};SystemBus.addEventListener('cheat:command',cmd);function draw(){x.fillStyle='#02050c';x.fillRect(0,0,420,420);grid(x);x.fillStyle='#fb7185';x.fillRect(f.x*cell+4,f.y*cell+4,cell-8,cell-8);s.forEach((p,i)=>{x.fillStyle=i?'#22d3ee':'#67e8f9';x.fillRect(p.x*cell+2,p.y*cell+2,cell-4,cell-4)})}draw();loop();w._cleanup=()=>{alive=false;clearTimeout(timer);off();SystemBus.removeEventListener('cheat:command',cmd)}}
function initBreakout(w){const c=w.querySelector('[data-game="breakout"]');if(!c)return;const x=c.getContext('2d');let p=170,balls=[{x:210,y:320,vx:3.2,vy:-3.2}],score=0,run=true,lives=cheat('breakout','infinite_lives')?999:1,raf;const bricks=Array.from({length:35},(_,i)=>({x:18+i%7*57,y:35+Math.floor(i/7)*25,w:49,h:16,a:true})),off=keyboardController({arrowleft:-1,a:-1,arrowright:1,d:1},m=>p=Math.max(0,Math.min(420-pw(),p+m*24)));function pw(){return cheat('breakout','wide_paddle')?120:80}const cmd=e=>{if(e.detail?.gameId!=='breakout')return;if(e.detail.modifier==='multiball'&&e.detail.active&&balls.length<3)balls.push({...balls[0],vx:-balls[0].vx,vy:balls[0].vy*1.05},{...balls[0],vx:balls[0].vx*.8,vy:-Math.abs(balls[0].vy)});if(e.detail.modifier==='infinite_lives'&&e.detail.active)lives=999};SystemBus.addEventListener('cheat:modifier',cmd);function frame(){if(!run)return;const sc=speed();for(const b of balls){b.x+=b.vx*sc;b.y+=b.vy*sc;if(b.x<7||b.x>413)b.vx*=-1;if(b.y<7)b.vy*=-1;if(b.y>386&&b.y<410&&b.x>p&&b.x<p+pw())b.vy=-Math.abs(b.vy);for(const q of bricks)if(q.a&&b.x>q.x&&b.x<q.x+q.w&&b.y>q.y&&b.y<q.y+q.h){q.a=false;b.vy*=-1;score++;break}}balls=balls.filter(b=>b.y<430);if(!balls.length){if(lives>1){if(lives<999)lives--;balls=[{x:210,y:320,vx:3.2,vy:-3.2}]}else{run=false;SystemBus.dispatchEvent(new CustomEvent('game:score',{detail:{id:'breakout',score}}));toast(`GAME OVER // SCORE ${score}`);return}}w.querySelector('[data-score]').textContent=score;draw();raf=requestAnimationFrame(frame)}function draw(){x.fillStyle='#02050c';x.fillRect(0,0,420,420);grid(x);bricks.forEach((b,i)=>{if(b.a){x.fillStyle=['#67e8f9','#a78bfa','#fb7185'][i%3];x.fillRect(b.x,b.y,b.w,b.h)}});x.fillStyle='#fff';x.fillRect(p,395,pw(),8);x.fillStyle='#facc15';balls.forEach(b=>{x.beginPath();x.arc(b.x,b.y,6,0,Math.PI*2);x.fill()})}draw();frame();w._cleanup=()=>{run=false;cancelAnimationFrame(raf);off();SystemBus.removeEventListener('cheat:modifier',cmd)}}
function initPong(w){const c=w.querySelector('[data-game="pong"]');if(!c)return;const x=c.getContext('2d');let p=170,ai=170,b={x:210,y:210,vx:4,vy:2.7},score=0,run=true,raf;const ph=()=>cheat('pong','paddle_boost')?120:80,off=keyboardController({arrowup:-1,w:-1,arrowdown:1,s:1},m=>p=Math.max(0,Math.min(420-ph(),p+m*(cheat('pong','paddle_boost')?40:28))));function reset(dir){const boost=cheat('pong','ball_speed')?1.45:1;b={x:210,y:210,vx:4*dir*boost,vy:(Math.random()>.5?1:-1)*2.8*boost}}function frame(){if(!run)return;const sc=speed(),ais=cheat('pong','ai_difficulty')?4.6:2.6;ai+=Math.sign(b.y-(ai+40))*ais*sc;ai=Math.max(0,Math.min(340,ai));b.x+=b.vx*sc;b.y+=b.vy*sc;if(b.y<6||b.y>414)b.vy*=-1;if(b.x<24&&b.y>p&&b.y<p+ph())b.vx=Math.abs(b.vx);if(b.x>396&&b.y>ai&&b.y<ai+80)b.vx=-Math.abs(b.vx);if(b.x>430){score++;reset(-1)}if(b.x<-10){score=Math.max(0,score-1);reset(1)}w.querySelector('[data-score]').textContent=score;draw();raf=requestAnimationFrame(frame)}function draw(){x.fillStyle='#02050c';x.fillRect(0,0,420,420);x.strokeStyle='rgba(103,232,249,.25)';x.setLineDash([8,10]);x.beginPath();x.moveTo(210,0);x.lineTo(210,420);x.stroke();x.setLineDash([]);x.fillStyle='#67e8f9';x.fillRect(12,p,8,ph());x.fillStyle='#fb7185';x.fillRect(400,ai,8,80);x.fillStyle='#facc15';x.beginPath();x.arc(b.x,b.y,6,0,Math.PI*2);x.fill()}draw();frame();w._cleanup=()=>{run=false;cancelAnimationFrame(raf);off()}}
function grid(x){x.strokeStyle='rgba(103,232,249,.055)';for(let i=0;i<=20;i++){x.beginPath();x.moveTo(i*21,0);x.lineTo(i*21,420);x.stroke();x.beginPath();x.moveTo(0,i*21);x.lineTo(420,i*21);x.stroke()}}
function cycleTheme(){const a=['','theme-violet','theme-amber'],c=a.indexOf(Storage.get('theme','')),n=a[(c+1)%a.length];document.body.classList.remove(...a.filter(Boolean));if(n)document.body.classList.add(n);Storage.set('theme',n)}function updateClock(){const c=document.querySelector('[data-clock]');if(c)c.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}function toast(t){let n=document.querySelector('.system-toast');if(!n){n=document.createElement('div');n.className='system-toast';n.style.cssText='position:fixed;right:18px;bottom:90px;z-index:999;padding:12px 15px;border:1px solid var(--line);border-radius:9px;background:rgba(5,10,24,.94);color:var(--cyan);font:700 .7rem JetBrains Mono;box-shadow:var(--shadow)';document.body.appendChild(n)}n.textContent=t;clearTimeout(n._timer);n._timer=setTimeout(()=>n.remove(),2600)}function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
const st=Storage.get('theme','');if(st)document.body.classList.add(st);if(Storage.get('reduceMotion',false))document.body.classList.add('reduce-motion');window.ArcadeOS={openApp,registerApp,registry:AppRegistry,bus:SystemBus,storage:Storage};